-- USM_REGION 


DROP TABLE REGION;


CREATE TABLE REGION(
    REGION_ID VARCHAR2(50) PRIMARY KEY NOT NULL   -- 지역명
)
;

INSERT INTO REGION  VALUES('서울특별시');
INSERT INTO REGION  VALUES('인천광역시');
INSERT INTO REGION  VALUES('대전광역시');
INSERT INTO REGION  VALUES('울산광역시');
INSERT INTO REGION  VALUES('부산광역시');
INSERT INTO REGION  VALUES('광주광역시');
INSERT INTO REGION  VALUES('경기도');
INSERT INTO REGION  VALUES('강원도');
INSERT INTO REGION  VALUES('충청도');
INSERT INTO REGION  VALUES('전라도');
INSERT INTO REGION  VALUES('경상도');
INSERT INTO REGION  VALUES('제주도');
COMMIT;


SELECT * FROM region;

