-- USM_REGION 


INSERT INTO REGION  VALUES(1,'서울특별시');
INSERT INTO REGION  VALUES(2,'인천광역시');
INSERT INTO REGION  VALUES(3,'대전광역시');
INSERT INTO REGION  VALUES(4,'울산광역시');
INSERT INTO REGION  VALUES(5,'부산광역시');
INSERT INTO REGION  VALUES(6,'광주광역시');
INSERT INTO REGION  VALUES(7,'경기도');
INSERT INTO REGION  VALUES(8,'강원도');
INSERT INTO REGION  VALUES(9,'충청도');
INSERT INTO REGION  VALUES(10,'전라도');
INSERT INTO REGION  VALUES(11,'경상도');
INSERT INTO REGION  VALUES(12,'제주도');
COMMIT;

